### ISSUE TITLE
potential instrumentation bypassing

### ISSUE THREAD

**Issue by StanPlatinum** [StanPlatinum/Deflection#2]
The instrumentation for memory write can be bypassed theoretically, if the attacker can build a function like below.

```c
int mem_write(unsigned long* addr, unsigned long hex) {
	unsigned long cond = 0;
    goto exp;
ins:
    //memory write operation
    *addr = hex;
    cond = 1;

exp:
    if(cond == 0) {
        //direct jump
        goto ins;
    }
out:
    return 0;
}
```

**Comment by StanPlatinum** [comment]
It's hard to mitigate this attack since one must use W+X memory if Deflection is built on SGX1.

**Comment by ya0guang** [comment]
After instrumentation, modify the assembly (binary) file to make `goto ins` jump to the middle of instrumented memory write (just before `mov`).
